### ISSUE TITLE
wrong value for agent_version with latest tag

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-network-agent#192]
**Versions**

v0.0.15-alpha

**Steps to reproduce**

1. use new tagged image for sending telemetry

**Additional context**

![agent version](https://github.com/honeycombio/honeycomb-network-agent/assets/29520003/14e72bbb-d4cb-440d-a836-888975b3efac)

**Comment by robbkidd** [comment]
Fixed in #206. 

We'd still like to compute build version from git tags, but GitHub's action/checkout used in the PR and Release workflows does not pull all tags by default. We'll need to tinker more with the workflows and the action configuration to get the CI build environment to know about our tags.
