### ISSUE TITLE
Configurable allow list of HTTP headers to record

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-network-agent#215]
The agent captures an hard-coded list of specific HTTP [request](https://github.com/honeycombio/honeycomb-network-agent/blob/c70537c26783f1ce25e97efc16b86862cf73b473/main.go#L121-L128) headers. Headers often include sensitive information that should not be recorded in telemetry, so we ought not record them all. Adding a configurable allow list of header names to record would allow users to selectively include headers they want the agent to record into events sent to Honeycomb.

**Comment by JamieDanielson** [comment]
Consider having a specific allow-list. Include user-agent by default, and show that in an example and encourage folks to always have it. We can do this like the OTEL_PROPAGATORS, which defaults to tracecontext,baggage and if that environment variable is updated it must include those explicitly if they are wanted, otherwise they will be overwritten.
Since this will likely be case-sensitive, be sure to document that.
